name: 'Todo'
description: '해야할 것이 생겼어요'
title: '📄 [Todo] - <title>'
body:
  - type: textarea
    attributes:
      label: Descrition
      description: |
        [Description] 할일의 설명을 작성해주세요.
      placeholder: |
        예) 마이페이지 퍼블리싱
  - type: textarea
    attributes:
      label: Additional
      description: |
        [추가사항] 별도로 알려줘야 할 사항이나 추가사항을 작성해주세요
